#-------------------------------------------------
#
# Project created by QtCreator 2018-05-10T13:59:36
#
#-------------------------------------------------

QT       -= core gui
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt

win32:CONFIG(debug,debug|release):TARGET = actuatorControllerd
else:win32:CONFIG(release,debug|release):TARGET = actuatorController
else:unix:TARGET = actuatorController

win32:CONFIG(debug,debug|release):DESTDIR = ../../ActuatorController_SDK/serialPort_Ethernet2CAN_sdk_v3.0.0/sdk/lib/windows_x64/debug
else:win32:CONFIG(release,debug|release):DESTDIR = ../../ActuatorController_SDK/serialPort_Ethernet2CAN_sdk_v3.0.0/sdk/lib/windows_x64/release
else:unix:DESTDIR = ../../ActuatorController_SDK/serialPort_Ethernet2CAN_sdk_v3.0.0/sdk/lib/linux_x86_64

TEMPLATE = lib

DEFINES += ACTUATORCONTROLLER_LIBRARY
DEFINES += ASIO_STANDALONE
DEFINES += ASIO_HAS_STD_CHRONO
#DEFINES += DEBUG_OUTPUT
#DEFINES += ASIO_DYN_LINK
#DEFINES += _WIN32_WINNT=0x0601
# The following define makes your compiler emit warnings if you use
# any feature of Qt which as been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

INCLUDEPATH += asio
INCLUDEPATH += serial/include

#自定义
DEFINES += USING_VECTOR
DEFINES += IMU_ENABLE

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += actuatorcontroller.cpp \
    AbstractAutoRecognize.cpp \
    actuatordata.cpp \
    communicateunit.cpp \
    communication.cpp \
    dataUtil.cpp \
    EthernetAutoRecognize.cpp \
    EthernetCommunicateUnit.cpp \
    EthernetCommunication.cpp \
    idata.cpp \
    innfosproxy.cpp \
    itimer.cpp \
    mediator.cpp \
    proxyparser.cpp \
    SerialAutoRecognize.cpp \
    SerialCommunicateUnit.cpp \
    SerialCommunication.cpp \
    #asio/asio/impl/src.cpp \
    serial/src/impl/list_ports/list_ports_linux.cc \
    serial/src/impl/list_ports/list_ports_osx.cc \
    serial/src/impl/list_ports/list_ports_win.cc \
    serial/src/impl/unix.cc \
    serial/src/impl/win.cc \
    serial/src/serial.cc \
    versionnumber.cpp

HEADERS += actuatorcontroller.h\
        actuatorcontroller_global.h \
    asio/asio/detail/impl/buffer_sequence_adapter.ipp \
    asio/asio/detail/impl/descriptor_ops.ipp \
    asio/asio/detail/impl/dev_poll_reactor.hpp \
    asio/asio/detail/impl/dev_poll_reactor.ipp \
    asio/asio/detail/impl/epoll_reactor.hpp \
    asio/asio/detail/impl/epoll_reactor.ipp \
    asio/asio/detail/impl/eventfd_select_interrupter.ipp \
    asio/asio/detail/impl/handler_tracking.ipp \
    asio/asio/detail/impl/kqueue_reactor.hpp \
    asio/asio/detail/impl/kqueue_reactor.ipp \
    asio/asio/detail/impl/null_event.ipp \
    asio/asio/detail/impl/pipe_select_interrupter.ipp \
    asio/asio/detail/impl/posix_event.ipp \
    asio/asio/detail/impl/posix_mutex.ipp \
    asio/asio/detail/impl/posix_thread.ipp \
    asio/asio/detail/impl/posix_tss_ptr.ipp \
    asio/asio/detail/impl/reactive_descriptor_service.ipp \
    asio/asio/detail/impl/reactive_serial_port_service.ipp \
    asio/asio/detail/impl/reactive_socket_service_base.ipp \
    asio/asio/detail/impl/resolver_service_base.ipp \
    asio/asio/detail/impl/scheduler.ipp \
    asio/asio/detail/impl/select_reactor.hpp \
    asio/asio/detail/impl/select_reactor.ipp \
    asio/asio/detail/impl/service_registry.hpp \
    asio/asio/detail/impl/service_registry.ipp \
    asio/asio/detail/impl/signal_set_service.ipp \
    asio/asio/detail/impl/socket_ops.ipp \
    asio/asio/detail/impl/socket_select_interrupter.ipp \
    asio/asio/detail/impl/strand_executor_service.hpp \
    asio/asio/detail/impl/strand_executor_service.ipp \
    asio/asio/detail/impl/strand_service.hpp \
    asio/asio/detail/impl/strand_service.ipp \
    asio/asio/detail/impl/throw_error.ipp \
    asio/asio/detail/impl/timer_queue_ptime.ipp \
    asio/asio/detail/impl/timer_queue_set.ipp \
    asio/asio/detail/impl/win_event.ipp \
    asio/asio/detail/impl/win_iocp_handle_service.ipp \
    asio/asio/detail/impl/win_iocp_io_context.hpp \
    asio/asio/detail/impl/win_iocp_io_context.ipp \
    asio/asio/detail/impl/win_iocp_serial_port_service.ipp \
    asio/asio/detail/impl/win_iocp_socket_service_base.ipp \
    asio/asio/detail/impl/win_mutex.ipp \
    asio/asio/detail/impl/win_object_handle_service.ipp \
    asio/asio/detail/impl/win_static_mutex.ipp \
    asio/asio/detail/impl/win_thread.ipp \
    asio/asio/detail/impl/win_tss_ptr.ipp \
    asio/asio/detail/impl/winrt_ssocket_service_base.ipp \
    asio/asio/detail/impl/winrt_timer_scheduler.hpp \
    asio/asio/detail/impl/winrt_timer_scheduler.ipp \
    asio/asio/detail/impl/winsock_init.ipp \
    asio/asio/detail/array.hpp \
    asio/asio/detail/array_fwd.hpp \
    asio/asio/detail/assert.hpp \
    asio/asio/detail/atomic_count.hpp \
    asio/asio/detail/base_from_completion_cond.hpp \
    asio/asio/detail/bind_handler.hpp \
    asio/asio/detail/buffer_resize_guard.hpp \
    asio/asio/detail/buffer_sequence_adapter.hpp \
    asio/asio/detail/buffered_stream_storage.hpp \
    asio/asio/detail/call_stack.hpp \
    asio/asio/detail/chrono.hpp \
    asio/asio/detail/chrono_time_traits.hpp \
    asio/asio/detail/completion_handler.hpp \
    asio/asio/detail/concurrency_hint.hpp \
    asio/asio/detail/conditionally_enabled_event.hpp \
    asio/asio/detail/conditionally_enabled_mutex.hpp \
    asio/asio/detail/config.hpp \
    asio/asio/detail/consuming_buffers.hpp \
    asio/asio/detail/cstddef.hpp \
    asio/asio/detail/cstdint.hpp \
    asio/asio/detail/date_time_fwd.hpp \
    asio/asio/detail/deadline_timer_service.hpp \
    asio/asio/detail/dependent_type.hpp \
    asio/asio/detail/descriptor_ops.hpp \
    asio/asio/detail/descriptor_read_op.hpp \
    asio/asio/detail/descriptor_write_op.hpp \
    asio/asio/detail/dev_poll_reactor.hpp \
    asio/asio/detail/epoll_reactor.hpp \
    asio/asio/detail/event.hpp \
    asio/asio/detail/eventfd_select_interrupter.hpp \
    asio/asio/detail/executor_op.hpp \
    asio/asio/detail/fd_set_adapter.hpp \
    asio/asio/detail/fenced_block.hpp \
    asio/asio/detail/functional.hpp \
    asio/asio/detail/gcc_arm_fenced_block.hpp \
    asio/asio/detail/gcc_hppa_fenced_block.hpp \
    asio/asio/detail/gcc_sync_fenced_block.hpp \
    asio/asio/detail/gcc_x86_fenced_block.hpp \
    asio/asio/detail/global.hpp \
    asio/asio/detail/handler_alloc_helpers.hpp \
    asio/asio/detail/handler_cont_helpers.hpp \
    asio/asio/detail/handler_invoke_helpers.hpp \
    asio/asio/detail/handler_tracking.hpp \
    asio/asio/detail/handler_type_requirements.hpp \
    asio/asio/detail/handler_work.hpp \
    asio/asio/detail/hash_map.hpp \
    asio/asio/detail/io_control.hpp \
    asio/asio/detail/is_buffer_sequence.hpp \
    asio/asio/detail/is_executor.hpp \
    asio/asio/detail/keyword_tss_ptr.hpp \
    asio/asio/detail/kqueue_reactor.hpp \
    asio/asio/detail/limits.hpp \
    asio/asio/detail/local_free_on_block_exit.hpp \
    asio/asio/detail/macos_fenced_block.hpp \
    asio/asio/detail/memory.hpp \
    asio/asio/detail/mutex.hpp \
    asio/asio/detail/noncopyable.hpp \
    asio/asio/detail/null_event.hpp \
    asio/asio/detail/null_fenced_block.hpp \
    asio/asio/detail/null_global.hpp \
    asio/asio/detail/null_mutex.hpp \
    asio/asio/detail/null_reactor.hpp \
    asio/asio/detail/null_signal_blocker.hpp \
    asio/asio/detail/null_socket_service.hpp \
    asio/asio/detail/null_static_mutex.hpp \
    asio/asio/detail/null_thread.hpp \
    asio/asio/detail/null_tss_ptr.hpp \
    asio/asio/detail/object_pool.hpp \
    asio/asio/detail/old_win_sdk_compat.hpp \
    asio/asio/detail/op_queue.hpp \
    asio/asio/detail/operation.hpp \
    asio/asio/detail/pipe_select_interrupter.hpp \
    asio/asio/detail/pop_options.hpp \
    asio/asio/detail/posix_event.hpp \
    asio/asio/detail/posix_fd_set_adapter.hpp \
    asio/asio/detail/posix_global.hpp \
    asio/asio/detail/posix_mutex.hpp \
    asio/asio/detail/posix_signal_blocker.hpp \
    asio/asio/detail/posix_static_mutex.hpp \
    asio/asio/detail/posix_thread.hpp \
    asio/asio/detail/posix_tss_ptr.hpp \
    asio/asio/detail/push_options.hpp \
    asio/asio/detail/reactive_descriptor_service.hpp \
    asio/asio/detail/reactive_null_buffers_op.hpp \
    asio/asio/detail/reactive_serial_port_service.hpp \
    asio/asio/detail/reactive_socket_accept_op.hpp \
    asio/asio/detail/reactive_socket_connect_op.hpp \
    asio/asio/detail/reactive_socket_recv_op.hpp \
    asio/asio/detail/reactive_socket_recvfrom_op.hpp \
    asio/asio/detail/reactive_socket_recvmsg_op.hpp \
    asio/asio/detail/reactive_socket_send_op.hpp \
    asio/asio/detail/reactive_socket_sendto_op.hpp \
    asio/asio/detail/reactive_socket_service.hpp \
    asio/asio/detail/reactive_socket_service_base.hpp \
    asio/asio/detail/reactive_wait_op.hpp \
    asio/asio/detail/reactor.hpp \
    asio/asio/detail/reactor_fwd.hpp \
    asio/asio/detail/reactor_op.hpp \
    asio/asio/detail/reactor_op_queue.hpp \
    asio/asio/detail/recycling_allocator.hpp \
    asio/asio/detail/regex_fwd.hpp \
    asio/asio/detail/resolve_endpoint_op.hpp \
    asio/asio/detail/resolve_op.hpp \
    asio/asio/detail/resolve_query_op.hpp \
    asio/asio/detail/resolver_service.hpp \
    asio/asio/detail/resolver_service_base.hpp \
    asio/asio/detail/scheduler.hpp \
    asio/asio/detail/scheduler_operation.hpp \
    asio/asio/detail/scheduler_thread_info.hpp \
    asio/asio/detail/scoped_lock.hpp \
    asio/asio/detail/scoped_ptr.hpp \
    asio/asio/detail/select_interrupter.hpp \
    asio/asio/detail/select_reactor.hpp \
    asio/asio/detail/service_registry.hpp \
    asio/asio/detail/signal_blocker.hpp \
    asio/asio/detail/signal_handler.hpp \
    asio/asio/detail/signal_init.hpp \
    asio/asio/detail/signal_op.hpp \
    asio/asio/detail/signal_set_service.hpp \
    asio/asio/detail/socket_holder.hpp \
    asio/asio/detail/socket_ops.hpp \
    asio/asio/detail/socket_option.hpp \
    asio/asio/detail/socket_select_interrupter.hpp \
    asio/asio/detail/socket_types.hpp \
    asio/asio/detail/solaris_fenced_block.hpp \
    asio/asio/detail/static_mutex.hpp \
    asio/asio/detail/std_event.hpp \
    asio/asio/detail/std_fenced_block.hpp \
    asio/asio/detail/std_global.hpp \
    asio/asio/detail/std_mutex.hpp \
    asio/asio/detail/std_static_mutex.hpp \
    asio/asio/detail/std_thread.hpp \
    asio/asio/detail/strand_executor_service.hpp \
    asio/asio/detail/strand_service.hpp \
    asio/asio/detail/string_view.hpp \
    asio/asio/detail/thread.hpp \
    asio/asio/detail/thread_context.hpp \
    asio/asio/detail/thread_group.hpp \
    asio/asio/detail/thread_info_base.hpp \
    asio/asio/detail/throw_error.hpp \
    asio/asio/detail/throw_exception.hpp \
    asio/asio/detail/timer_queue.hpp \
    asio/asio/detail/timer_queue_base.hpp \
    asio/asio/detail/timer_queue_ptime.hpp \
    asio/asio/detail/timer_queue_set.hpp \
    asio/asio/detail/timer_scheduler.hpp \
    asio/asio/detail/timer_scheduler_fwd.hpp \
    asio/asio/detail/tss_ptr.hpp \
    asio/asio/detail/type_traits.hpp \
    asio/asio/detail/variadic_templates.hpp \
    asio/asio/detail/wait_handler.hpp \
    asio/asio/detail/wait_op.hpp \
    asio/asio/detail/win_event.hpp \
    asio/asio/detail/win_fd_set_adapter.hpp \
    asio/asio/detail/win_fenced_block.hpp \
    asio/asio/detail/win_global.hpp \
    asio/asio/detail/win_iocp_handle_read_op.hpp \
    asio/asio/detail/win_iocp_handle_service.hpp \
    asio/asio/detail/win_iocp_handle_write_op.hpp \
    asio/asio/detail/win_iocp_io_context.hpp \
    asio/asio/detail/win_iocp_null_buffers_op.hpp \
    asio/asio/detail/win_iocp_operation.hpp \
    asio/asio/detail/win_iocp_overlapped_op.hpp \
    asio/asio/detail/win_iocp_overlapped_ptr.hpp \
    asio/asio/detail/win_iocp_serial_port_service.hpp \
    asio/asio/detail/win_iocp_socket_accept_op.hpp \
    asio/asio/detail/win_iocp_socket_connect_op.hpp \
    asio/asio/detail/win_iocp_socket_recv_op.hpp \
    asio/asio/detail/win_iocp_socket_recvfrom_op.hpp \
    asio/asio/detail/win_iocp_socket_recvmsg_op.hpp \
    asio/asio/detail/win_iocp_socket_send_op.hpp \
    asio/asio/detail/win_iocp_socket_service.hpp \
    asio/asio/detail/win_iocp_socket_service_base.hpp \
    asio/asio/detail/win_iocp_thread_info.hpp \
    asio/asio/detail/win_iocp_wait_op.hpp \
    asio/asio/detail/win_mutex.hpp \
    asio/asio/detail/win_object_handle_service.hpp \
    asio/asio/detail/win_static_mutex.hpp \
    asio/asio/detail/win_thread.hpp \
    asio/asio/detail/win_tss_ptr.hpp \
    asio/asio/detail/winapp_thread.hpp \
    asio/asio/detail/wince_thread.hpp \
    asio/asio/detail/winrt_async_manager.hpp \
    asio/asio/detail/winrt_async_op.hpp \
    asio/asio/detail/winrt_resolve_op.hpp \
    asio/asio/detail/winrt_resolver_service.hpp \
    asio/asio/detail/winrt_socket_connect_op.hpp \
    asio/asio/detail/winrt_socket_recv_op.hpp \
    asio/asio/detail/winrt_socket_send_op.hpp \
    asio/asio/detail/winrt_ssocket_service.hpp \
    asio/asio/detail/winrt_ssocket_service_base.hpp \
    asio/asio/detail/winrt_timer_scheduler.hpp \
    asio/asio/detail/winrt_utils.hpp \
    asio/asio/detail/winsock_init.hpp \
    asio/asio/detail/work_dispatcher.hpp \
    asio/asio/detail/wrapped_handler.hpp \
    asio/asio/experimental/impl/co_spawn.hpp \
    asio/asio/experimental/impl/detached.hpp \
    asio/asio/experimental/impl/redirect_error.hpp \
    asio/asio/experimental/co_spawn.hpp \
    asio/asio/experimental/detached.hpp \
    asio/asio/experimental/redirect_error.hpp \
    asio/asio/generic/detail/impl/endpoint.ipp \
    asio/asio/generic/detail/endpoint.hpp \
    asio/asio/generic/basic_endpoint.hpp \
    asio/asio/generic/datagram_protocol.hpp \
    asio/asio/generic/raw_protocol.hpp \
    asio/asio/generic/seq_packet_protocol.hpp \
    asio/asio/generic/stream_protocol.hpp \
    asio/asio/impl/buffered_read_stream.hpp \
    asio/asio/impl/buffered_write_stream.hpp \
    asio/asio/impl/connect.hpp \
    asio/asio/impl/defer.hpp \
    asio/asio/impl/dispatch.hpp \
    asio/asio/impl/error.ipp \
    asio/asio/impl/error_code.ipp \
    asio/asio/impl/execution_context.hpp \
    asio/asio/impl/execution_context.ipp \
    asio/asio/impl/executor.hpp \
    asio/asio/impl/executor.ipp \
    asio/asio/impl/handler_alloc_hook.ipp \
    asio/asio/impl/io_context.hpp \
    asio/asio/impl/io_context.ipp \
    asio/asio/impl/post.hpp \
    asio/asio/impl/read.hpp \
    asio/asio/impl/read_at.hpp \
    asio/asio/impl/read_until.hpp \
    asio/asio/impl/serial_port_base.hpp \
    asio/asio/impl/serial_port_base.ipp \
    asio/asio/impl/spawn.hpp \
    asio/asio/impl/src.hpp \
    asio/asio/impl/system_context.hpp \
    asio/asio/impl/system_context.ipp \
    asio/asio/impl/system_executor.hpp \
    asio/asio/impl/thread_pool.hpp \
    asio/asio/impl/thread_pool.ipp \
    asio/asio/impl/use_future.hpp \
    asio/asio/impl/write.hpp \
    asio/asio/impl/write_at.hpp \
    asio/asio/ip/detail/impl/endpoint.ipp \
    asio/asio/ip/detail/endpoint.hpp \
    asio/asio/ip/detail/socket_option.hpp \
    asio/asio/ip/impl/address.hpp \
    asio/asio/ip/impl/address.ipp \
    asio/asio/ip/impl/address_v4.hpp \
    asio/asio/ip/impl/address_v4.ipp \
    asio/asio/ip/impl/address_v6.hpp \
    asio/asio/ip/impl/address_v6.ipp \
    asio/asio/ip/impl/basic_endpoint.hpp \
    asio/asio/ip/impl/host_name.ipp \
    asio/asio/ip/impl/network_v4.hpp \
    asio/asio/ip/impl/network_v4.ipp \
    asio/asio/ip/impl/network_v6.hpp \
    asio/asio/ip/impl/network_v6.ipp \
    asio/asio/ip/address.hpp \
    asio/asio/ip/address_v4.hpp \
    asio/asio/ip/address_v4_iterator.hpp \
    asio/asio/ip/address_v4_range.hpp \
    asio/asio/ip/address_v6.hpp \
    asio/asio/ip/address_v6_iterator.hpp \
    asio/asio/ip/address_v6_range.hpp \
    asio/asio/ip/bad_address_cast.hpp \
    asio/asio/ip/basic_endpoint.hpp \
    asio/asio/ip/basic_resolver.hpp \
    asio/asio/ip/basic_resolver_entry.hpp \
    asio/asio/ip/basic_resolver_iterator.hpp \
    asio/asio/ip/basic_resolver_query.hpp \
    asio/asio/ip/basic_resolver_results.hpp \
    asio/asio/ip/host_name.hpp \
    asio/asio/ip/icmp.hpp \
    asio/asio/ip/multicast.hpp \
    asio/asio/ip/network_v4.hpp \
    asio/asio/ip/network_v6.hpp \
    asio/asio/ip/resolver_base.hpp \
    asio/asio/ip/resolver_query_base.hpp \
    asio/asio/ip/resolver_service.hpp \
    asio/asio/ip/tcp.hpp \
    asio/asio/ip/udp.hpp \
    asio/asio/ip/unicast.hpp \
    asio/asio/ip/v6_only.hpp \
    asio/asio/local/detail/impl/endpoint.ipp \
    asio/asio/local/detail/endpoint.hpp \
    asio/asio/local/basic_endpoint.hpp \
    asio/asio/local/connect_pair.hpp \
    asio/asio/local/datagram_protocol.hpp \
    asio/asio/local/stream_protocol.hpp \
    asio/asio/posix/basic_descriptor.hpp \
    asio/asio/posix/basic_stream_descriptor.hpp \
    asio/asio/posix/descriptor.hpp \
    asio/asio/posix/descriptor_base.hpp \
    asio/asio/posix/stream_descriptor.hpp \
    asio/asio/posix/stream_descriptor_service.hpp \
    asio/asio/ssl/detail/impl/engine.ipp \
    asio/asio/ssl/detail/impl/openssl_init.ipp \
    asio/asio/ssl/detail/buffered_handshake_op.hpp \
    asio/asio/ssl/detail/engine.hpp \
    asio/asio/ssl/detail/handshake_op.hpp \
    asio/asio/ssl/detail/io.hpp \
    asio/asio/ssl/detail/openssl_init.hpp \
    asio/asio/ssl/detail/openssl_types.hpp \
    asio/asio/ssl/detail/password_callback.hpp \
    asio/asio/ssl/detail/read_op.hpp \
    asio/asio/ssl/detail/shutdown_op.hpp \
    asio/asio/ssl/detail/stream_core.hpp \
    asio/asio/ssl/detail/verify_callback.hpp \
    asio/asio/ssl/detail/write_op.hpp \
    asio/asio/ssl/impl/context.hpp \
    asio/asio/ssl/impl/context.ipp \
    asio/asio/ssl/impl/error.ipp \
    asio/asio/ssl/impl/rfc2818_verification.ipp \
    asio/asio/ssl/impl/src.hpp \
    asio/asio/ssl/context.hpp \
    asio/asio/ssl/context_base.hpp \
    asio/asio/ssl/error.hpp \
    asio/asio/ssl/rfc2818_verification.hpp \
    asio/asio/ssl/stream.hpp \
    asio/asio/ssl/stream_base.hpp \
    asio/asio/ssl/verify_context.hpp \
    asio/asio/ssl/verify_mode.hpp \
    asio/asio/ts/buffer.hpp \
    asio/asio/ts/executor.hpp \
    asio/asio/ts/internet.hpp \
    asio/asio/ts/io_context.hpp \
    asio/asio/ts/net.hpp \
    asio/asio/ts/netfwd.hpp \
    asio/asio/ts/socket.hpp \
    asio/asio/ts/timer.hpp \
    asio/asio/windows/basic_handle.hpp \
    asio/asio/windows/basic_object_handle.hpp \
    asio/asio/windows/basic_random_access_handle.hpp \
    asio/asio/windows/basic_stream_handle.hpp \
    asio/asio/windows/object_handle.hpp \
    asio/asio/windows/object_handle_service.hpp \
    asio/asio/windows/overlapped_handle.hpp \
    asio/asio/windows/overlapped_ptr.hpp \
    asio/asio/windows/random_access_handle.hpp \
    asio/asio/windows/random_access_handle_service.hpp \
    asio/asio/windows/stream_handle.hpp \
    asio/asio/windows/stream_handle_service.hpp \
    asio/asio/associated_allocator.hpp \
    asio/asio/associated_executor.hpp \
    asio/asio/async_result.hpp \
    asio/asio/basic_datagram_socket.hpp \
    asio/asio/basic_deadline_timer.hpp \
    asio/asio/basic_io_object.hpp \
    asio/asio/basic_raw_socket.hpp \
    asio/asio/basic_seq_packet_socket.hpp \
    asio/asio/basic_serial_port.hpp \
    asio/asio/basic_signal_set.hpp \
    asio/asio/basic_socket.hpp \
    asio/asio/basic_socket_acceptor.hpp \
    asio/asio/basic_socket_iostream.hpp \
    asio/asio/basic_socket_streambuf.hpp \
    asio/asio/basic_stream_socket.hpp \
    asio/asio/basic_streambuf.hpp \
    asio/asio/basic_streambuf_fwd.hpp \
    asio/asio/basic_waitable_timer.hpp \
    asio/asio/bind_executor.hpp \
    asio/asio/buffer.hpp \
    asio/asio/buffered_read_stream.hpp \
    asio/asio/buffered_read_stream_fwd.hpp \
    asio/asio/buffered_stream.hpp \
    asio/asio/buffered_stream_fwd.hpp \
    asio/asio/buffered_write_stream.hpp \
    asio/asio/buffered_write_stream_fwd.hpp \
    asio/asio/buffers_iterator.hpp \
    asio/asio/completion_condition.hpp \
    asio/asio/connect.hpp \
    asio/asio/coroutine.hpp \
    asio/asio/datagram_socket_service.hpp \
    asio/asio/deadline_timer.hpp \
    asio/asio/deadline_timer_service.hpp \
    asio/asio/defer.hpp \
    asio/asio/dispatch.hpp \
    asio/asio/error.hpp \
    asio/asio/error_code.hpp \
    asio/asio/execution_context.hpp \
    asio/asio/executor.hpp \
    asio/asio/executor_work_guard.hpp \
    asio/asio/experimental.hpp \
    asio/asio/handler_alloc_hook.hpp \
    asio/asio/handler_continuation_hook.hpp \
    asio/asio/handler_invoke_hook.hpp \
    asio/asio/handler_type.hpp \
    asio/asio/high_resolution_timer.hpp \
    asio/asio/io_context.hpp \
    asio/asio/io_context_strand.hpp \
    asio/asio/io_service.hpp \
    asio/asio/io_service_strand.hpp \
    asio/asio/is_executor.hpp \
    asio/asio/is_read_buffered.hpp \
    asio/asio/is_write_buffered.hpp \
    asio/asio/packaged_task.hpp \
    asio/asio/placeholders.hpp \
    asio/asio/post.hpp \
    asio/asio/raw_socket_service.hpp \
    asio/asio/read.hpp \
    asio/asio/read_at.hpp \
    asio/asio/read_until.hpp \
    asio/asio/seq_packet_socket_service.hpp \
    asio/asio/serial_port.hpp \
    asio/asio/serial_port_base.hpp \
    asio/asio/serial_port_service.hpp \
    asio/asio/signal_set.hpp \
    asio/asio/signal_set_service.hpp \
    asio/asio/socket_acceptor_service.hpp \
    asio/asio/socket_base.hpp \
    asio/asio/spawn.hpp \
    asio/asio/ssl.hpp \
    asio/asio/steady_timer.hpp \
    asio/asio/strand.hpp \
    asio/asio/stream_socket_service.hpp \
    asio/asio/streambuf.hpp \
    asio/asio/system_context.hpp \
    asio/asio/system_error.hpp \
    asio/asio/system_executor.hpp \
    asio/asio/system_timer.hpp \
    asio/asio/thread.hpp \
    asio/asio/thread_pool.hpp \
    asio/asio/time_traits.hpp \
    asio/asio/unyield.hpp \
    asio/asio/use_future.hpp \
    asio/asio/uses_executor.hpp \
    asio/asio/version.hpp \
    asio/asio/wait_traits.hpp \
    asio/asio/waitable_timer_service.hpp \
    asio/asio/write.hpp \
    asio/asio/write_at.hpp \
    asio/asio/yield.hpp \
    asio/asio.hpp \
    CSignal.hpp \
    AbstractAutoRecognize.h \
    actuatordata.h \
    actuatordefine.h \
    communicateunit.h \
    communication.h \
    dataUtil.h \
    EthernetAutoRecognize.h \
    EthernetCommunicateUnit.h \
    EthernetCommunication.h \
    idata.h \
    innfosproxy.h \
    itimer.h \
    mediator.h \
    proxyparser.h \
    SerialAutoRecognize.h \
    SerialCommunicateUnit.h \
    SerialCommunication.h \
    serial/include/serial/impl/unix.h \
    serial/include/serial/impl/win.h \
    serial/include/serial/serial.h \
    v8stdint.h \
    stringformat.h \
    versionnumber.h

unix {
    target.path = /usr/lib
    INSTALLS += target
}
